#!/usr/bin/env python3

import hashlib
import gzip
import sys
import os


# in the future, replace Bio to reduce dependancy
from Bio.SeqIO import parse

suffix_zps = '.zps'
suffix_hls = '.hls'

def fncore(fname, fmt = 'auto', seqtype = None):
    # seqtype has not been implemented

    # auto-detect gbk / fasta
    if fmt == 'auto':
        line = open(fname).readline()
        if line.strip().startswith('>'):
            fmt = 'fasta'
        elif line.strip().startswith('LOCUS'):
            fmt = 'genbank'
    
    bname = os.path.splitext(fname)[0]
    hlsfile = open(bname+suffix_hls, 'w')
    for rec in parse(fname, fmt):
        seq = rec.seq.tostring().upper().encode('ascii')
        name = rec.id
        sha1 = hashlib.sha1(seq).hexdigest()

        zpsname = sha1 + suffix_zps

        print(sha1, name, sep = '\t', file=hlsfile)
        with gzip.open(zpsname, 'wb') as zps:
            zps.write(seq) 

    hlsfile.close()

if __name__ == "__main__":
    for fname in sys.argv[1:]:
        fncore(fname)
